import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/installation'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/authentication',
        'guides/consumption-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'CLI',
          link: { type: 'doc', id: 'reference/cli/overview' },
          items: [{ type: 'autogenerated', dirName: 'reference/cli' }],
        },
        {
          type: 'category',
          label: 'Extension',
          items: [{ type: 'autogenerated', dirName: 'reference/extension' }],
        },
        {
          type: 'category',
          label: 'Libraries',
          link: { type: 'doc', id: 'reference/libraries/overview' },
          items: [{ type: 'autogenerated', dirName: 'reference/libraries' }],
        },
        {
          type: 'category',
          label: 'MCP',
          link: { type: 'doc', id: 'reference/mcp/overview' },
          items: [{ type: 'autogenerated', dirName: 'reference/mcp' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/index',
        'contributing/style-guide',
        'contributing/cross-repo',
      ],
    },
  ],
};

export default sidebars;
